### ISSUE TITLE
how to use the code for medical image segmentation like BRATS dataset?

### ISSUE THREAD

**Issue by ghost** [hfslyc/AdvSemiSeg#29]

**Comment by watchmexiang** [comment]
Hello, I have the same question. Have you trained your data set with it, thank you @zhoutonxgue @hfslyc

**Comment by Eason270** [comment]
Nowadays,Did anyone successfully apply it to the medical image dataset?

**Comment by colindecourt** [comment]
Hi, 
To apply this code to a medical image dataset you just have to load your own dataset using PyTorch.utils.data package. You can get inspired by the original code used to load VOC or Pascal datasets. 
Be carefull to one things, the segmentor is a ResNet network which takes RGB images as input. So convert you grayscale images in RGB before feeding the network and it will works. 
I hope this will help you.

**Comment by Eason270** [comment]
Thank you！I will have a try later.Again,thanks for your contribution!

**Comment by tuscasp** [comment]
I imagine that it should be enough to pass the argument `--data-dir` to the train.py script, with the file structure copying the one from VOC2012 and voc_list directories?
Unfortunately, I have been trying to do it but without success so far. Please, share how you manage to use other datasets of yours to the task.

**Comment by colindecourt** [comment]
For my work I didn't used the same structure as VOC2012 and voc_list directories. I write a new script just like `voc_dataset.py` with my own dataset, my own pre-processing functions and include it in the `train.py` script. 
I think you should detach yourself from the original way to load and use the dataset because VOC2012 dataset is quite different from others medical dataset. 
I don't know if it helps you. Good luck
